# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Smatt's Code
description: >- # this means to ignore newlines until "baseurl:"
  Sharing my adventures, successful or not. Helping you to avoid the pitfalls (I will undoubtably fall in!) and sharing the shortcuts I (hopefully) find that can benefit your projects.  And have a laugh along the way.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.smattscode.co.uk" # the base hostname & protocol for your site, e.g. http://example.com

# StartOf JEKYLL-SEO-TAG
locale: en-GB
tagline: Sharing my adventures and mishaps in the techie world to help you.
logo: /assets/img/branding/TextFlatIconAbove_Orig.svg
# Site Twitter Details
twitter:
  username: smattscode
  card: summary
# Site Author
author:
  name: Smatt
  email: 
  picture: /assets/img/branding/IconOnly_Orig.svg
  url: https://www.smattscode.co.uk
  twitter: smattscode
  links:
  - title: Twitter
    url: https://twitter.com/smattscode
    icon: fab fa-twitter-square
  - title: Instagram
    url: https://instagram.com/smattscode
    icon: fab fa-instagram
  - title: Pinterest
    url: https://Pinterest.com/smattscode
    icon: fab fa-pinterest    
  - title: GitHub
    url: https://github.com/smattscode
    icon: fab fa-github
#  - title: Feed
#    url: atom.xml
#    icon: fas fa-rss-square
# EndOf JEKYLL-SEO-TAG  

# StartOf GitHub Pages
#  lsi: false
#  safe: true
#  source: ""
#  incremental: false
#  highlighter: rouge
#  gist:
#    noscript: false
#  kramdown:
#    math_engine: mathjax
#    syntax_highlighter: rouge
# EndOf GitHub Pages

# Front Matter Defaults
defaults:
  # Post defaults
  - scope:
      path: "_posts"
      type: posts
    values:
      layout: post
      comments: true
      share: true

# Footer Links
footer_links:
  - title: Twitter
    url: https://twitter.com/smattscode
    icon: fab fa-twitter-square
  - title: Instagram
    url: https://instagram.com/smattscode
    icon: fab fa-instagram
  - title: Pinterest
    url: https://Pinterest.com/smattscode
    icon: fab fa-pinterest    
  - title: GitHub
    url: https://github.com/smattscode
    icon: fab fa-github
#  - title: Feed
#    url: atom.xml
#    icon: fas fa-rss-square

# Build settings
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

  # StartOf GitHub Pages Plugins
  #   jekyll-coffeescript
  #   jekyll-default-layout
  #   jekyll-gist
  #   jekyll-github-metadata
  #   jekyll-optional-front-matter
  #   jekyll-paginate
  #   jekyll-readme-index
  #   jekyll-titles-from-headings
  #   jekyll-relative-links
  # EndOf GitHub Pages Plugins
    
# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
